// Python -> Rust converter (compiler front-end + Rust back-end).
//
// Scanner/parser: generated by ANTLR4 (C++ target) from the grammars in
// grammar/.  This file walks the resulting parse tree and emits Rust source.
//
// Dynamic typing model
// ---------------------
// Python is dynamically typed, so the generated Rust represents *every* runtime
// value with a single tagged-union type `Value` (see the runtime prelude below).
// Variables, parameters, return values and collection elements are all `Value`;
// arithmetic, comparison, indexing, truthiness, iteration and the built-in
// functions all dispatch on the variant at run time. This means type
// annotations are optional, a variable may hold different types over its
// lifetime, and collections may mix element types -- exactly like Python.

#include "antlr4-runtime.h"
#include "PythonRustLexer.h"
#include "PythonRustParser.h"

#include <cctype>
#include <cstdlib>
#include <fstream>
#include <iostream>
#include <set>
#include <sstream>
#include <string>
#include <vector>

using P = PythonRustParser;

// ---------------------------------------------------------------------------
// Runtime prelude: a tiny dynamically-typed value model, emitted verbatim at
// the top of every generated .rs file.
// ---------------------------------------------------------------------------
static const char *PRELUDE = R"RUST(#![allow(dead_code, unused_variables, unused_mut, unused_parens, unused_imports,
         non_snake_case, unreachable_code, unused_assignments, path_statements)]
use std::cell::RefCell;
use std::rc::Rc;

#[derive(Clone)]
enum Value {
    None,
    Int(i64),
    Float(f64),
    Bool(bool),
    Str(String),
    List(Rc<RefCell<Vec<Value>>>),
    Tuple(Vec<Value>),
    Dict(Rc<RefCell<Vec<(Value, Value)>>>),
    Set(Rc<RefCell<Vec<Value>>>),
}

fn values_equal(a: &Value, b: &Value) -> bool {
    match (a, b) {
        (Value::None, Value::None) => true,
        (Value::Int(x), Value::Int(y)) => x == y,
        (Value::Float(x), Value::Float(y)) => x == y,
        (Value::Int(x), Value::Float(y)) => (*x as f64) == *y,
        (Value::Float(x), Value::Int(y)) => *x == (*y as f64),
        (Value::Bool(x), Value::Bool(y)) => x == y,
        (Value::Str(x), Value::Str(y)) => x == y,
        (Value::Tuple(x), Value::Tuple(y)) => {
            x.len() == y.len() && x.iter().zip(y.iter()).all(|(p, q)| values_equal(p, q))
        }
        (Value::List(x), Value::List(y)) | (Value::Set(x), Value::Set(y)) => {
            let x = x.borrow();
            let y = y.borrow();
            x.len() == y.len() && x.iter().zip(y.iter()).all(|(p, q)| values_equal(p, q))
        }
        _ => false,
    }
}

impl Value {
    fn list(v: Vec<Value>) -> Value { Value::List(Rc::new(RefCell::new(v))) }
    fn set(v: Vec<Value>) -> Value {
        let mut out: Vec<Value> = Vec::new();
        for item in v {
            if !out.iter().any(|e| values_equal(e, &item)) { out.push(item); }
        }
        Value::Set(Rc::new(RefCell::new(out)))
    }
    fn dict(pairs: Vec<(Value, Value)>) -> Value {
        let mut out: Vec<(Value, Value)> = Vec::new();
        for (k, v) in pairs {
            if let Some(slot) = out.iter_mut().find(|p| values_equal(&p.0, &k)) {
                slot.1 = v;
            } else {
                out.push((k, v));
            }
        }
        Value::Dict(Rc::new(RefCell::new(out)))
    }

    fn is_truthy(&self) -> bool {
        match self {
            Value::None => false,
            Value::Bool(b) => *b,
            Value::Int(n) => *n != 0,
            Value::Float(f) => *f != 0.0,
            Value::Str(s) => !s.is_empty(),
            Value::Tuple(v) => !v.is_empty(),
            Value::List(v) | Value::Set(v) => !v.borrow().is_empty(),
            Value::Dict(d) => !d.borrow().is_empty(),
        }
    }

    fn to_f64(&self) -> f64 {
        match self {
            Value::Int(n) => *n as f64,
            Value::Float(f) => *f,
            Value::Bool(b) => if *b { 1.0 } else { 0.0 },
            _ => panic!("not a number"),
        }
    }
    fn as_index(&self) -> i64 {
        match self {
            Value::Int(n) => *n,
            Value::Bool(b) => if *b { 1 } else { 0 },
            _ => panic!("index must be an integer"),
        }
    }

    fn add(&self, other: &Value) -> Value {
        match (self, other) {
            (Value::Int(a), Value::Int(b)) => Value::Int(a + b),
            (Value::Str(a), Value::Str(b)) => Value::Str(format!("{}{}", a, b)),
            (Value::Tuple(a), Value::Tuple(b)) => {
                let mut v = a.clone();
                v.extend(b.iter().cloned());
                Value::Tuple(v)
            }
            (Value::List(a), Value::List(b)) => {
                let mut v = a.borrow().clone();
                v.extend(b.borrow().iter().cloned());
                Value::list(v)
            }
            _ => Value::Float(self.to_f64() + other.to_f64()),
        }
    }
    fn sub(&self, other: &Value) -> Value {
        match (self, other) {
            (Value::Int(a), Value::Int(b)) => Value::Int(a - b),
            _ => Value::Float(self.to_f64() - other.to_f64()),
        }
    }
    fn mul(&self, other: &Value) -> Value {
        match (self, other) {
            (Value::Int(a), Value::Int(b)) => Value::Int(a * b),
            (Value::Str(a), Value::Int(b)) => Value::Str(a.repeat((*b).max(0) as usize)),
            _ => Value::Float(self.to_f64() * other.to_f64()),
        }
    }
    fn div(&self, other: &Value) -> Value { Value::Float(self.to_f64() / other.to_f64()) }
    fn rem(&self, other: &Value) -> Value {
        match (self, other) {
            (Value::Int(a), Value::Int(b)) => Value::Int(a % b),
            _ => Value::Float(self.to_f64() % other.to_f64()),
        }
    }
    fn neg(&self) -> Value {
        match self {
            Value::Int(a) => Value::Int(-a),
            Value::Float(a) => Value::Float(-a),
            _ => panic!("bad operand for unary -"),
        }
    }

    fn eq_(&self, other: &Value) -> Value { Value::Bool(values_equal(self, other)) }
    fn ne_(&self, other: &Value) -> Value { Value::Bool(!values_equal(self, other)) }
    fn order(&self, other: &Value) -> std::cmp::Ordering {
        match (self, other) {
            (Value::Str(a), Value::Str(b)) => a.cmp(b),
            _ => self.to_f64().partial_cmp(&other.to_f64()).unwrap_or(std::cmp::Ordering::Equal),
        }
    }
    fn lt(&self, o: &Value) -> Value { Value::Bool(self.order(o) == std::cmp::Ordering::Less) }
    fn gt(&self, o: &Value) -> Value { Value::Bool(self.order(o) == std::cmp::Ordering::Greater) }
    fn le(&self, o: &Value) -> Value { Value::Bool(self.order(o) != std::cmp::Ordering::Greater) }
    fn ge(&self, o: &Value) -> Value { Value::Bool(self.order(o) != std::cmp::Ordering::Less) }

    fn index(&self, key: &Value) -> Value {
        match self {
            Value::List(v) | Value::Set(v) => {
                let v = v.borrow();
                let mut i = key.as_index();
                if i < 0 { i += v.len() as i64; }
                v[i as usize].clone()
            }
            Value::Tuple(v) => {
                let mut i = key.as_index();
                if i < 0 { i += v.len() as i64; }
                v[i as usize].clone()
            }
            Value::Str(s) => {
                let chars: Vec<char> = s.chars().collect();
                let mut i = key.as_index();
                if i < 0 { i += chars.len() as i64; }
                Value::Str(chars[i as usize].to_string())
            }
            Value::Dict(d) => {
                let d = d.borrow();
                for (k, val) in d.iter() {
                    if values_equal(k, key) { return val.clone(); }
                }
                panic!("KeyError");
            }
            _ => panic!("value is not subscriptable"),
        }
    }
    fn set_index(&self, key: &Value, val: Value) {
        match self {
            Value::List(v) => {
                let mut v = v.borrow_mut();
                let mut i = key.as_index();
                if i < 0 { i += v.len() as i64; }
                v[i as usize] = val;
            }
            Value::Dict(d) => {
                let mut d = d.borrow_mut();
                for pair in d.iter_mut() {
                    if values_equal(&pair.0, key) { pair.1 = val; return; }
                }
                d.push((key.clone(), val));
            }
            _ => panic!("value does not support item assignment"),
        }
    }
    fn slice(&self, lo: &Value, hi: &Value) -> Value {
        let items = self.iter_values();
        let n = items.len() as i64;
        let mut a = match lo { Value::None => 0, _ => lo.as_index() };
        let mut b = match hi { Value::None => n, _ => hi.as_index() };
        if a < 0 { a += n; }
        if b < 0 { b += n; }
        a = a.max(0).min(n);
        b = b.max(0).min(n);
        let mut out: Vec<Value> = Vec::new();
        let mut i = a;
        while i < b { out.push(items[i as usize].clone()); i += 1; }
        if let Value::Str(_) = self {
            let s: String = out.iter().map(|v| match v { Value::Str(c) => c.clone(), _ => String::new() }).collect();
            return Value::Str(s);
        }
        Value::list(out)
    }
    fn append(&self, val: Value) {
        match self {
            Value::List(v) => v.borrow_mut().push(val),
            Value::Set(v) => {
                let mut v = v.borrow_mut();
                if !v.iter().any(|e| values_equal(e, &val)) { v.push(val); }
            }
            _ => panic!("value has no append"),
        }
    }
    fn len(&self) -> i64 {
        match self {
            Value::Str(s) => s.chars().count() as i64,
            Value::Tuple(v) => v.len() as i64,
            Value::List(v) | Value::Set(v) => v.borrow().len() as i64,
            Value::Dict(d) => d.borrow().len() as i64,
            _ => panic!("value has no len()"),
        }
    }
    fn iter_values(&self) -> Vec<Value> {
        match self {
            Value::List(v) | Value::Set(v) => v.borrow().clone(),
            Value::Tuple(v) => v.clone(),
            Value::Str(s) => s.chars().map(|c| Value::Str(c.to_string())).collect(),
            Value::Dict(d) => d.borrow().iter().map(|(k, _)| k.clone()).collect(),
            _ => panic!("value is not iterable"),
        }
    }

    fn show(&self, quote: bool) -> String {
        match self {
            Value::None => "None".to_string(),
            Value::Bool(b) => if *b { "True".to_string() } else { "False".to_string() },
            Value::Int(n) => n.to_string(),
            Value::Float(f) => {
                if f.fract() == 0.0 && f.is_finite() { format!("{:.1}", f) } else { format!("{}", f) }
            }
            Value::Str(s) => if quote { format!("'{}'", s) } else { s.clone() },
            Value::List(v) => {
                let v = v.borrow();
                let parts: Vec<String> = v.iter().map(|e| e.show(true)).collect();
                format!("[{}]", parts.join(", "))
            }
            Value::Set(v) => {
                let v = v.borrow();
                let parts: Vec<String> = v.iter().map(|e| e.show(true)).collect();
                format!("{{{}}}", parts.join(", "))
            }
            Value::Tuple(v) => {
                let parts: Vec<String> = v.iter().map(|e| e.show(true)).collect();
                if v.len() == 1 { format!("({},)", parts[0]) } else { format!("({})", parts.join(", ")) }
            }
            Value::Dict(d) => {
                let d = d.borrow();
                let parts: Vec<String> = d.iter()
                    .map(|(k, val)| format!("{}: {}", k.show(true), val.show(true)))
                    .collect();
                format!("{{{}}}", parts.join(", "))
            }
        }
    }
}

impl std::fmt::Display for Value {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}", self.show(false))
    }
}

fn py_print(args: &[Value]) {
    let parts: Vec<String> = args.iter().map(|a| a.show(false)).collect();
    println!("{}", parts.join(" "));
}
fn py_len(v: &Value) -> Value { Value::Int(v.len()) }
fn py_str(v: &Value) -> Value { Value::Str(v.show(false)) }
fn py_int(v: &Value) -> Value {
    match v {
        Value::Int(n) => Value::Int(*n),
        Value::Float(f) => Value::Int(*f as i64),
        Value::Bool(b) => Value::Int(if *b { 1 } else { 0 }),
        Value::Str(s) => Value::Int(s.trim().parse::<i64>().unwrap_or(0)),
        _ => panic!("int(): bad argument"),
    }
}
fn py_float(v: &Value) -> Value { Value::Float(v.to_f64()) }
fn py_abs(v: &Value) -> Value {
    match v {
        Value::Int(n) => Value::Int(n.abs()),
        Value::Float(f) => Value::Float(f.abs()),
        _ => panic!("abs(): bad argument"),
    }
}
fn py_min(a: &Value, b: &Value) -> Value {
    if a.order(b) == std::cmp::Ordering::Greater { b.clone() } else { a.clone() }
}
fn py_max(a: &Value, b: &Value) -> Value {
    if a.order(b) == std::cmp::Ordering::Less { b.clone() } else { a.clone() }
}
fn py_range(args: &[Value]) -> Value {
    let (start, stop, step) = match args.len() {
        1 => (0, args[0].as_index(), 1),
        2 => (args[0].as_index(), args[1].as_index(), 1),
        _ => (args[0].as_index(), args[1].as_index(), args[2].as_index()),
    };
    let mut out: Vec<Value> = Vec::new();
    let mut i = start;
    if step > 0 { while i < stop { out.push(Value::Int(i)); i += step; } }
    else if step < 0 { while i > stop { out.push(Value::Int(i)); i += step; } }
    Value::list(out)
}

)RUST";

// ---------------------------------------------------------------------------
// Small helpers
// ---------------------------------------------------------------------------

static bool isRustKeyword(const std::string &s) {
    static const std::set<std::string> kw = {
        "as", "break", "const", "continue", "crate", "dyn", "else", "enum",
        "extern", "false", "fn", "for", "if", "impl", "in", "let", "loop",
        "match", "mod", "move", "mut", "pub", "ref", "return", "self", "Self",
        "static", "struct", "super", "trait", "true", "type", "unsafe", "use",
        "where", "while", "async", "await", "box", "macro", "override", "try",
        "union", "Value"};
    return kw.count(s) != 0;
}

static std::string ident(const std::string &name) {
    if (name == "self" || name == "Self" || name == "crate" || name == "super")
        return name;
    if (isRustKeyword(name)) return "r#" + name;
    return name;
}

// Convert a Python string literal token to a Rust string literal (quotes only).
static std::string convertString(const std::string &lit) {
    if (lit.size() >= 6 &&
        (lit.compare(0, 3, "\"\"\"") == 0 || lit.compare(0, 3, "'''") == 0)) {
        std::string body = lit.substr(3, lit.size() - 6);
        std::string out = "\"";
        for (char c : body) {
            if (c == '"') out += "\\\"";
            else if (c == '\\') out += "\\\\";
            else if (c == '\n') out += "\\n";
            else if (c == '\r') out += "\\r";
            else out += c;
        }
        return out + "\"";
    }
    if (lit.empty()) return "\"\"";
    char q = lit.front();
    if (q == '"') return lit;  // already a Rust-compatible double-quoted literal
    std::string body = lit.substr(1, lit.size() - 2);
    std::string out = "\"";
    for (char c : body) {
        if (c == '"') out += "\\\"";
        else out += c;
    }
    return out + "\"";
}

static std::string normalizeFloat(const std::string &t) {
    std::string s = t;
    if (!s.empty() && s.front() == '.') s = "0" + s;
    if (!s.empty() && s.back() == '.') s += "0";
    return s;
}

static std::string join(const std::vector<std::string> &v, const std::string &sep) {
    std::string r;
    for (size_t i = 0; i < v.size(); i++) {
        if (i) r += sep;
        r += v[i];
    }
    return r;
}

// ---------------------------------------------------------------------------
// Code generator
// ---------------------------------------------------------------------------

class RustGen {
public:
    std::string generate(P::ProgramContext *prog) {
        collectSignatures(prog);
        std::string items;
        std::string mainBody;

        for (auto *st : prog->stmt()) {
            if (auto *cs = st->compound_stmt()) {
                if (auto *fd = cs->funcdef()) {
                    level_ = 0;
                    items += genFuncdef(fd, "");
                    items += "\n";
                    continue;
                }
                if (auto *cd = cs->classdef()) {
                    level_ = 0;
                    items += genClassdef(cd);
                    items += "\n";
                    continue;
                }
                if (auto *ifs = cs->if_stmt(); ifs && isMainGuard(ifs)) {
                    level_ = 1;
                    genSuite(ifs->suite(0), mainBody);
                    continue;
                }
            }
            level_ = 1;
            genStmt(st, mainBody);
        }

        std::string out = PRELUDE;
        out += items;
        if (!mainBody.empty())
            out += "fn main() {\n" + mainBody + "}\n";
        else
            out += "fn main() {}\n";
        return out;
    }

private:
    int level_ = 0;
    int cnt_ = 0;
    std::set<std::string> declared_;
    std::set<std::string> classNames_;

    std::string pad() const { return std::string(level_ * 4, ' '); }
    std::string tmp(const std::string &p) { return p + std::to_string(cnt_++); }

    void collectSignatures(P::ProgramContext *prog) {
        for (auto *st : prog->stmt())
            if (auto *cs = st->compound_stmt())
                if (auto *cd = cs->classdef())
                    classNames_.insert(cd->ID()->getText());
    }

    // ---- functions / classes ---------------------------------------------
    std::string genFuncdef(P::FuncdefContext *fd, const std::string &selfKind) {
        auto saved = declared_;
        declared_.clear();

        std::vector<std::string> params;
        if (!selfKind.empty()) params.push_back(selfKind);
        if (auto *ps = fd->parameters()) {
            for (auto *p : ps->param()) {
                std::string pn = p->ID()->getText();
                if (pn == "self") continue;
                declared_.insert(pn);
                params.push_back(ident(pn) + ": Value");
            }
        }
        std::string sig = pad() + "fn " + ident(fd->ID()->getText()) + "(" +
                          join(params, ", ") + ") -> Value {\n";
        std::string body;
        level_++;
        genSuite(fd->suite(), body);
        body += pad() + "Value::None\n";
        level_--;
        declared_ = saved;
        return sig + body + pad() + "}\n";
    }

    std::string genClassdef(P::ClassdefContext *cd) {
        std::string name = cd->ID()->getText();
        std::vector<P::FuncdefContext *> methods;
        std::vector<std::string> fields;
        std::set<std::string> seen;

        auto *suite = cd->suite();
        std::vector<P::StmtContext *> body;
        if (!suite->simple_stmt()) body = suite->stmt();
        for (auto *st : body)
            if (auto *cs = st->compound_stmt())
                if (auto *fd = cs->funcdef()) methods.push_back(fd);
        for (auto *m : methods) collectFields(m->suite(), fields, seen);

        std::string out = "#[derive(Clone)]\n";
        out += "struct " + ident(name) + " {\n";
        for (auto &f : fields) out += "    " + ident(f) + ": Value,\n";
        out += "}\n\n";
        out += "impl " + ident(name) + " {\n";
        level_ = 1;
        for (auto *m : methods) {
            if (m->ID()->getText() == "__init__")
                out += genConstructor(m, name, fields);
            else
                out += genFuncdef(m, methodMutatesSelf(m->suite()) ? "&mut self" : "&self");
            out += "\n";
        }
        level_ = 0;
        return out + "}\n";
    }

    std::string genConstructor(P::FuncdefContext *fd, const std::string &cls,
                               const std::vector<std::string> &fields) {
        auto saved = declared_;
        declared_.clear();
        std::vector<std::string> params;
        if (auto *ps = fd->parameters())
            for (auto *p : ps->param()) {
                std::string pn = p->ID()->getText();
                if (pn == "self") continue;
                declared_.insert(pn);
                params.push_back(ident(pn) + ": Value");
            }
        std::string sig = pad() + "fn new(" + join(params, ", ") + ") -> Self {\n";

        std::vector<std::pair<std::string, std::string>> inits;
        collectInits(fd->suite(), inits);
        std::set<std::string> set;
        level_++;
        std::string body = pad() + ident(cls) + " {\n";
        level_++;
        for (auto &kv : inits) {
            body += pad() + ident(kv.first) + ": " + kv.second + ",\n";
            set.insert(kv.first);
        }
        for (auto &f : fields)
            if (!set.count(f)) body += pad() + ident(f) + ": Value::None,\n";
        level_--;
        body += pad() + "}\n";
        level_--;
        declared_ = saved;
        return sig + body + pad() + "}\n";
    }

    void collectInits(P::SuiteContext *suite,
                      std::vector<std::pair<std::string, std::string>> &out) {
        if (suite->simple_stmt()) return;
        for (auto *st : suite->stmt()) {
            auto *ss = st->simple_stmt();
            if (!ss) continue;
            auto *es = ss->small_stmt()->expr_stmt();
            if (!es || es->ASSIGN().empty() || es->annassign()) continue;
            auto *lhs = es->testlist(0);
            if (lhs->expr().size() != 1) continue;
            auto *me = dynamic_cast<P::MemberExprContext *>(lhs->expr(0));
            if (!me || exprText(me->expr()) != "self") continue;
            out.push_back({me->ID()->getText(), genRhs(es->testlist().back())});
        }
    }
    void collectFields(P::SuiteContext *suite, std::vector<std::string> &fields,
                       std::set<std::string> &seen) {
        std::vector<std::pair<std::string, std::string>> inits;
        collectInits(suite, inits);
        for (auto &kv : inits)
            if (!seen.count(kv.first)) { seen.insert(kv.first); fields.push_back(kv.first); }
    }
    bool methodMutatesSelf(P::SuiteContext *suite) {
        std::vector<std::pair<std::string, std::string>> inits;
        collectInits(suite, inits);
        return !inits.empty();
    }

    // ---- statements -------------------------------------------------------
    void genSuite(P::SuiteContext *s, std::string &out) {
        if (auto *ss = s->simple_stmt()) { genSimple(ss, out); return; }
        for (auto *st : s->stmt()) genStmt(st, out);
    }
    void genStmt(P::StmtContext *st, std::string &out) {
        if (auto *ss = st->simple_stmt()) { genSimple(ss, out); return; }
        genCompound(st->compound_stmt(), out);
    }
    void genSimple(P::Simple_stmtContext *ss, std::string &out) {
        auto *sm = ss->small_stmt();
        if (auto *es = sm->expr_stmt()) {
            genExprStmt(es, out);
        } else if (auto *rs = sm->return_stmt()) {
            if (auto *tl = rs->testlist())
                out += pad() + "return " + genRhs(tl) + ";\n";
            else
                out += pad() + "return Value::None;\n";
        } else if (sm->pass_stmt()) {
            out += pad() + "// pass\n";
        } else if (auto *fs = sm->flow_stmt()) {
            out += pad() + (fs->BREAK() ? "break;\n" : "continue;\n");
        } else if (sm->raise_stmt()) {
            out += pad() + "panic!(\"exception raised\");\n";
        } else if (auto *im = sm->import_stmt()) {
            out += pad() + "// " + im->getText() + "\n";
        }
    }

    void genExprStmt(P::Expr_stmtContext *es, std::string &out) {
        if (auto *ann = es->annassign()) {
            std::string target = exprText(es->testlist(0)->expr(0));
            std::string rhs = ann->testlist() ? genRhs(ann->testlist()) : "Value::None";
            if (declared_.count(target))
                out += pad() + ident(target) + " = " + rhs + ";\n";
            else {
                out += pad() + "let mut " + ident(target) + " = " + rhs + ";\n";
                declared_.insert(target);
            }
            return;
        }
        if (es->ASSIGN().empty()) {  // bare expression statement
            out += pad() + "let _ = " + genExpr(es->testlist(0)->expr(0)) + ";\n";
            return;
        }
        auto tls = es->testlist();
        std::string rhs = genRhs(tls.back());
        for (size_t i = 0; i + 1 < tls.size(); i++) assignTarget(tls[i], rhs, out);
    }

    void assignTarget(P::TestlistContext *lhs, const std::string &rhs, std::string &out) {
        if (lhs->expr().size() > 1 || !lhs->COMMA().empty()) {
            std::string t = tmp("__t");
            out += pad() + "let " + t + " = " + rhs + ";\n";
            auto exprs = lhs->expr();
            for (size_t j = 0; j < exprs.size(); j++)
                assignSingle(exprs[j],
                             t + ".index(&Value::Int(" + std::to_string(j) + "))", out);
            return;
        }
        assignSingle(lhs->expr(0), rhs, out);
    }

    void assignSingle(P::ExprContext *e, const std::string &val, std::string &out) {
        if (auto *id = asIdAtom(e)) {
            std::string n = id->ID()->getText();
            if (declared_.count(n))
                out += pad() + ident(n) + " = " + val + ";\n";
            else {
                out += pad() + "let mut " + ident(n) + " = " + val + ";\n";
                declared_.insert(n);
            }
        } else if (auto *ie = dynamic_cast<P::IndexExprContext *>(e)) {
            if (ie->subscript()->slice()) {
                out += pad() + "// slice assignment is not supported\n";
                return;
            }
            out += pad() + "(" + genExpr(ie->expr()) + ").set_index(&(" +
                   genExpr(ie->subscript()->expr()) + "), " + val + ");\n";
        } else {
            out += pad() + genExpr(e) + " = " + val + ";\n";  // member target
        }
    }

    void genCompound(P::Compound_stmtContext *cs, std::string &out) {
        if (auto *i = cs->if_stmt()) return genIf(i, out);
        if (auto *w = cs->while_stmt()) return genWhile(w, out);
        if (auto *f = cs->for_stmt()) return genFor(f, out);
        if (auto *t = cs->try_stmt()) return genTry(t, out);
        if (auto *fd = cs->funcdef()) { out += genFuncdef(fd, ""); return; }
        if (auto *cd = cs->classdef()) { out += genClassdef(cd); return; }
    }

    void genIf(P::If_stmtContext *i, std::string &out) {
        auto e = i->expr();
        auto s = i->suite();
        out += pad() + "if (" + genExpr(e[0]) + ").is_truthy() {\n";
        level_++; genSuite(s[0], out); level_--;
        size_t si = 1;
        for (size_t k = 0; k < i->ELIF().size(); k++, si++) {
            out += pad() + "} else if (" + genExpr(e[si]) + ").is_truthy() {\n";
            level_++; genSuite(s[si], out); level_--;
        }
        if (i->ELSE()) {
            out += pad() + "} else {\n";
            level_++; genSuite(s.back(), out); level_--;
        }
        out += pad() + "}\n";
    }
    void genWhile(P::While_stmtContext *w, std::string &out) {
        out += pad() + "while (" + genExpr(w->expr()) + ").is_truthy() {\n";
        level_++; genSuite(w->suite(0), out); level_--;
        out += pad() + "}\n";
    }
    void genFor(P::For_stmtContext *f, std::string &out) {
        std::vector<std::string> names;
        flattenTargets(f->target_list(), names);
        auto *tl = f->testlist();
        std::string iter = (tl->expr().size() == 1) ? genExpr(tl->expr(0)) : genRhs(tl);
        if (names.size() == 1) {
            declared_.insert(names[0]);
            out += pad() + "for " + ident(names[0]) + " in (" + iter + ").iter_values() {\n";
            level_++; genSuite(f->suite(0), out); level_--;
        } else {
            std::string it = tmp("__item");
            out += pad() + "for " + it + " in (" + iter + ").iter_values() {\n";
            level_++;
            for (size_t j = 0; j < names.size(); j++) {
                declared_.insert(names[j]);
                out += pad() + "let mut " + ident(names[j]) + " = " + it +
                       ".index(&Value::Int(" + std::to_string(j) + "));\n";
            }
            genSuite(f->suite(0), out);
            level_--;
        }
        out += pad() + "}\n";
    }
    void genTry(P::Try_stmtContext *t, std::string &out) {
        out += pad() + "// try/except approximated (Rust has no exceptions)\n";
        out += pad() + "{\n";
        level_++; genSuite(t->suite(0), out); level_--;
        out += pad() + "}\n";
        if (t->FINALLY()) {
            out += pad() + "// finally:\n";
            genSuite(t->suite().back(), out);
        }
    }

    // ---- expressions ------------------------------------------------------
    // genExpr: a Value-typed expression, fine to *borrow* (no clone).
    std::string genExpr(P::ExprContext *e) {
        if (auto *c = dynamic_cast<P::AtomExprContext *>(e)) return genAtom(c->atom());
        if (auto *c = dynamic_cast<P::CallExprContext *>(e)) return genCall(c);
        if (auto *c = dynamic_cast<P::IndexExprContext *>(e)) return genIndex(c);
        if (auto *c = dynamic_cast<P::MemberExprContext *>(e))
            return genExpr(c->expr()) + "." + ident(c->ID()->getText());
        if (auto *c = dynamic_cast<P::UnaryExprContext *>(e)) {
            std::string in = genExpr(c->expr());
            return c->MINUS() ? "(" + in + ").neg()" : in;
        }
        if (auto *c = dynamic_cast<P::MulDivExprContext *>(e)) {
            std::string m = c->STAR() ? "mul" : (c->DIV() ? "div" : "rem");
            return "(" + genExpr(c->expr(0)) + ")." + m + "(&(" + genExpr(c->expr(1)) + "))";
        }
        if (auto *c = dynamic_cast<P::AddSubExprContext *>(e)) {
            std::string m = c->PLUS() ? "add" : "sub";
            return "(" + genExpr(c->expr(0)) + ")." + m + "(&(" + genExpr(c->expr(1)) + "))";
        }
        if (auto *c = dynamic_cast<P::CompExprContext *>(e)) {
            std::string m = c->LT() ? "lt" : c->GT() ? "gt" : c->LE() ? "le"
                          : c->GE() ? "ge" : c->EQ() ? "eq_" : "ne_";
            return "(" + genExpr(c->expr(0)) + ")." + m + "(&(" + genExpr(c->expr(1)) + "))";
        }
        if (auto *c = dynamic_cast<P::NotExprContext *>(e))
            return "Value::Bool(!(" + genExpr(c->expr()) + ").is_truthy())";
        if (auto *c = dynamic_cast<P::AndExprContext *>(e))
            return "Value::Bool((" + genExpr(c->expr(0)) + ").is_truthy() && (" +
                   genExpr(c->expr(1)) + ").is_truthy())";
        if (auto *c = dynamic_cast<P::OrExprContext *>(e))
            return "Value::Bool((" + genExpr(c->expr(0)) + ").is_truthy() || (" +
                   genExpr(c->expr(1)) + ").is_truthy())";
        return "Value::None";
    }

    // genValue: an *owned* Value (clones place expressions so the original is
    // not moved). Used wherever a value is stored or passed by value.
    std::string genValue(P::ExprContext *e) {
        if (asIdAtom(e) || dynamic_cast<P::MemberExprContext *>(e))
            return genExpr(e) + ".clone()";
        return genExpr(e);
    }

    std::string genAtom(P::AtomContext *a) {
        if (auto *c = dynamic_cast<P::IntAtomContext *>(a))
            return "Value::Int(" + c->INT()->getText() + ")";
        if (auto *c = dynamic_cast<P::FloatAtomContext *>(a))
            return "Value::Float(" + normalizeFloat(c->FLOAT()->getText()) + ")";
        if (auto *c = dynamic_cast<P::StringAtomContext *>(a))
            return "Value::Str(" + convertString(c->STRING()->getText()) + ".to_string())";
        if (dynamic_cast<P::TrueAtomContext *>(a)) return "Value::Bool(true)";
        if (dynamic_cast<P::FalseAtomContext *>(a)) return "Value::Bool(false)";
        if (dynamic_cast<P::NoneAtomContext *>(a)) return "Value::None";
        if (auto *c = dynamic_cast<P::IdAtomContext *>(a)) return ident(c->ID()->getText());
        if (auto *c = dynamic_cast<P::ListAtomContext *>(a)) return genList(c->list_maker());
        if (auto *c = dynamic_cast<P::SetDictAtomContext *>(a)) return genSetOrDict(c->set_or_dict());
        if (auto *c = dynamic_cast<P::GroupOrTupleAtomContext *>(a)) {
            auto *tl = c->testlist();
            if (!tl) return "Value::Tuple(vec![])";  // empty tuple ()
            if (tl->expr().size() > 1 || !tl->COMMA().empty()) return genRhs(tl);  // tuple
            return "(" + genExpr(tl->expr(0)) + ")";  // parenthesised expression
        }
        return "Value::None";
    }

    std::string genCall(P::CallExprContext *c) {
        if (auto *id = asIdAtom(c->expr())) {
            std::string fn = id->ID()->getText();
            auto pe = posArgExprs(c->arglist());
            if (fn == "print") return "py_print(&[" + valueArgs(pe) + "])";
            if (fn == "range") return "py_range(&[" + valueArgs(pe) + "])";
            if (fn == "len" && pe.size() == 1) return "py_len(&(" + genExpr(pe[0]) + "))";
            if (fn == "str" && pe.size() == 1) return "py_str(&(" + genExpr(pe[0]) + "))";
            if (fn == "int" && pe.size() == 1) return "py_int(&(" + genExpr(pe[0]) + "))";
            if (fn == "float" && pe.size() == 1) return "py_float(&(" + genExpr(pe[0]) + "))";
            if (fn == "abs" && pe.size() == 1) return "py_abs(&(" + genExpr(pe[0]) + "))";
            if (fn == "min" && pe.size() == 2)
                return "py_min(&(" + genExpr(pe[0]) + "), &(" + genExpr(pe[1]) + "))";
            if (fn == "max" && pe.size() == 2)
                return "py_max(&(" + genExpr(pe[0]) + "), &(" + genExpr(pe[1]) + "))";
            std::vector<std::string> a;
            for (auto *x : pe) a.push_back(genValue(x));
            if (classNames_.count(fn)) return ident(fn) + "::new(" + join(a, ", ") + ")";
            return ident(fn) + "(" + join(a, ", ") + ")";
        }
        if (auto *m = dynamic_cast<P::MemberExprContext *>(c->expr())) {
            auto pe = posArgExprs(c->arglist());
            std::vector<std::string> a;
            for (auto *x : pe) a.push_back(genValue(x));
            return "(" + genExpr(m->expr()) + ")." + ident(m->ID()->getText()) +
                   "(" + join(a, ", ") + ")";
        }
        auto pe = posArgExprs(c->arglist());
        std::vector<std::string> a;
        for (auto *x : pe) a.push_back(genValue(x));
        return "(" + genExpr(c->expr()) + ")(" + join(a, ", ") + ")";
    }

    std::string genIndex(P::IndexExprContext *c) {
        std::string base = genExpr(c->expr());
        auto *sub = c->subscript();
        if (auto *sl = sub->slice()) {
            std::string lo = "&Value::None", hi = "&Value::None";
            int colon = 0;
            for (auto *ch : sl->children) {
                if (ch->getText() == ":") { colon++; continue; }
                if (auto *ex = dynamic_cast<P::ExprContext *>(ch)) {
                    std::string v = "&(" + genExpr(ex) + ")";
                    if (colon == 0) lo = v; else if (colon == 1) hi = v;
                }
            }
            return "(" + base + ").slice(" + lo + ", " + hi + ")";
        }
        return "(" + base + ").index(&(" + genExpr(sub->expr()) + "))";
    }

    // ---- collections / comprehensions -------------------------------------
    std::string genList(P::List_makerContext *lm) {
        if (lm->comp_clause())
            return genComp(genValue(lm->expr(0)), "Vec<Value>", "Value::list", lm->comp_clause());
        std::vector<std::string> parts;
        for (auto *e : lm->expr()) parts.push_back(genValue(e));
        return "Value::list(vec![" + join(parts, ", ") + "])";
    }
    std::string genSetOrDict(P::Set_or_dictContext *sd) {
        bool isDict = !sd->dict_kv().empty();
        if (sd->comp_clause()) {
            if (isDict) {
                auto *kv = sd->dict_kv(0);
                std::string push = "(" + genValue(kv->expr(0)) + ", " + genValue(kv->expr(1)) + ")";
                return genComp(push, "Vec<(Value, Value)>", "Value::dict", sd->comp_clause());
            }
            return genComp(genValue(sd->expr(0)), "Vec<Value>", "Value::set", sd->comp_clause());
        }
        if (isDict) {
            std::vector<std::string> parts;
            for (auto *kv : sd->dict_kv())
                parts.push_back("(" + genValue(kv->expr(0)) + ", " + genValue(kv->expr(1)) + ")");
            return "Value::dict(vec![" + join(parts, ", ") + "])";
        }
        auto exprs = sd->expr();
        if (exprs.empty()) return "Value::dict(vec![])";  // {} is an empty dict
        std::vector<std::string> parts;
        for (auto *e : exprs) parts.push_back(genValue(e));
        return "Value::set(vec![" + join(parts, ", ") + "])";
    }

    std::string genComp(const std::string &pushExpr, const std::string &accTy,
                        const std::string &ctor, P::Comp_clauseContext *cc) {
        std::vector<std::string> names;
        flattenTargets(cc->target_list(), names);
        std::string iter = genExpr(cc->expr(0));
        std::string acc = tmp("__acc");
        std::string loopvar, prefix;
        if (names.size() == 1) {
            loopvar = ident(names[0]);
        } else {
            std::string it = tmp("__i");
            loopvar = it;
            for (size_t j = 0; j < names.size(); j++)
                prefix += "let " + ident(names[j]) + " = " + it +
                          ".index(&Value::Int(" + std::to_string(j) + ")); ";
        }
        std::string s = "{ let mut " + acc + ": " + accTy + " = Vec::new(); for " +
                        loopvar + " in (" + iter + ").iter_values() { " + prefix;
        if (cc->IF())
            s += "if (" + genExpr(cc->expr(1)) + ").is_truthy() { " + acc + ".push(" + pushExpr + "); } ";
        else
            s += acc + ".push(" + pushExpr + "); ";
        s += "} " + ctor + "(" + acc + ") }";
        return s;
    }

    // ---- testlist / targets / helpers -------------------------------------
    std::string genRhs(P::TestlistContext *tl) {
        if (tl->expr().size() > 1 || !tl->COMMA().empty()) {
            std::vector<std::string> parts;
            for (auto *e : tl->expr()) parts.push_back(genValue(e));
            return "Value::Tuple(vec![" + join(parts, ", ") + "])";
        }
        return genValue(tl->expr(0));
    }

    void flattenTargets(P::Target_listContext *tl, std::vector<std::string> &out) {
        for (auto *t : tl->target()) {
            if (t->ID()) out.push_back(t->ID()->getText());
            else if (t->target_list()) flattenTargets(t->target_list(), out);
        }
    }

    std::vector<P::ExprContext *> posArgExprs(P::ArglistContext *al) {
        std::vector<P::ExprContext *> out;
        if (!al) return out;
        for (auto *arg : al->argument()) {
            if (auto *pa = dynamic_cast<P::PosArgContext *>(arg)) out.push_back(pa->expr());
            else if (auto *ka = dynamic_cast<P::KwArgContext *>(arg)) out.push_back(ka->expr());
        }
        return out;
    }
    std::string valueArgs(const std::vector<P::ExprContext *> &es) {
        std::vector<std::string> a;
        for (auto *e : es) a.push_back(genValue(e));
        return join(a, ", ");
    }

    static P::IdAtomContext *asIdAtom(P::ExprContext *e) {
        if (auto *ae = dynamic_cast<P::AtomExprContext *>(e))
            return dynamic_cast<P::IdAtomContext *>(ae->atom());
        return nullptr;
    }
    std::string exprText(P::ExprContext *e) {
        if (auto *id = asIdAtom(e)) return id->ID()->getText();
        return genExpr(e);
    }
    static bool isMainGuard(P::If_stmtContext *i) {
        auto *cmp = dynamic_cast<P::CompExprContext *>(i->expr(0));
        if (!cmp || !cmp->EQ()) return false;
        std::string t = cmp->getText();
        return t.find("__name__") != std::string::npos &&
               t.find("__main__") != std::string::npos;
    }
};

// ---------------------------------------------------------------------------
// Conversion entry point (shared by the CLI and the web server)
// ---------------------------------------------------------------------------
class CollectingErrorListener : public antlr4::BaseErrorListener {
public:
    struct Err { size_t line; size_t col; std::string msg; };
    std::vector<Err> errors;  // both lexer and parser errors land here
    void syntaxError(antlr4::Recognizer *, antlr4::Token *, size_t line,
                     size_t col, const std::string &msg, std::exception_ptr) override {
        errors.push_back({line, col, msg});
    }
};

static std::vector<std::string> splitLines(const std::string &s) {
    std::vector<std::string> lines;
    std::string cur;
    for (char c : s) {
        if (c == '\n') { lines.push_back(cur); cur.clear(); }
        else if (c != '\r') cur += c;
    }
    lines.push_back(cur);
    return lines;
}

// Build a human-friendly, compiler-style report: each error shows its
// location, the message, the offending source line and a caret.
static std::string formatErrors(const std::vector<CollectingErrorListener::Err> &errs,
                                const std::string &source) {
    auto lines = splitLines(source);
    std::string r;
    size_t shown = 0;
    for (const auto &e : errs) {
        if (shown++ >= 50) { r += "... (further errors omitted)\n\n"; break; }
        r += "line " + std::to_string(e.line) + ":" + std::to_string(e.col + 1) +
             ": " + e.msg + "\n";
        if (e.line >= 1 && e.line <= lines.size()) {
            const std::string &src = lines[e.line - 1];
            r += "    " + src + "\n";
            r += "    " + std::string(e.col, ' ') + "^\n";
        }
        r += "\n";
    }
    r += std::to_string(errs.size()) +
         (errs.size() == 1 ? " error.\n" : " errors.\n");
    return r;
}

// Returns true on success (out = Rust). On failure, err = formatted error report.
// Non-static: also called from the web server translation unit (webserver.cpp).
bool convertSource(const std::string &source, std::string &out, std::string &err) {
    antlr4::ANTLRInputStream input(source);
    PythonRustLexer lexer(&input);
    antlr4::CommonTokenStream tokens(&lexer);
    PythonRustParser parser(&tokens);

    CollectingErrorListener listener;
    lexer.removeErrorListeners();
    parser.removeErrorListeners();
    lexer.addErrorListener(&listener);   // capture token-level errors too
    parser.addErrorListener(&listener);

    P::ProgramContext *tree = parser.program();
    if (!listener.errors.empty()) {
        err = formatErrors(listener.errors, source);
        return false;
    }
    RustGen gen;
    out = gen.generate(tree);
    return true;
}

// Implemented in webserver.cpp (isolated from ANTLR headers to avoid the
// <windows.h> macro clashes, e.g. ERROR / IN).
int runServer(int port);

// ---------------------------------------------------------------------------
// Driver
// ---------------------------------------------------------------------------
int main(int argc, char **argv) {
    if (argc < 2) {
        std::cerr << "Usage:\n"
                  << "  pyrust <input.py> [-o output.rs]   convert a file\n"
                  << "  pyrust --serve [port]              launch the web UI\n";
        return 2;
    }

    std::string first = argv[1];
    if (first == "--serve") {
        int port = (argc >= 3) ? std::atoi(argv[2]) : 8756;
        return runServer(port);
    }

    std::string inPath = first;
    std::string outPath;
    for (int i = 2; i < argc; i++) {
        std::string a = argv[i];
        if (a == "-o" && i + 1 < argc) outPath = argv[++i];
    }
    if (outPath.empty()) {
        outPath = inPath;
        auto dot = outPath.find_last_of('.');
        if (dot != std::string::npos) outPath = outPath.substr(0, dot);
        outPath += ".rs";
    }

    std::ifstream ifs(inPath, std::ios::binary);
    if (!ifs) { std::cerr << "Cannot open input file: " << inPath << "\n"; return 2; }
    std::stringstream buf;
    buf << ifs.rdbuf();

    std::string rust, err;
    if (!convertSource(buf.str(), rust, err)) {
        std::cerr << err << "Aborting due to syntax error(s).\n";
        return 1;
    }
    std::ofstream ofs(outPath, std::ios::binary);
    if (!ofs) { std::cerr << "Cannot write output file: " << outPath << "\n"; return 2; }
    ofs << rust;
    std::cerr << "Wrote " << outPath << "\n";
    return 0;
}
