// Python -> Rust converter (compiler front-end + Rust back-end).
//
// Scanner/parser: generated by ANTLR4 (C++ target) from the grammars in
// grammar/.  This file walks the resulting parse tree and emits Rust source.
//
// The translator targets the statically typed subset described in README.md:
// type-annotated functions, control flow, arithmetic/boolean/comparison
// expressions, lists / dicts / sets, comprehensions, classes, try/except and
// (the focus of this grammar extension) Python tuples.

#include "antlr4-runtime.h"
#include "PythonRustLexer.h"
#include "PythonRustParser.h"

#include <fstream>
#include <iostream>
#include <set>
#include <sstream>
#include <string>
#include <vector>

using P = PythonRustParser;

// ---------------------------------------------------------------------------
// Small helpers
// ---------------------------------------------------------------------------

static bool isRustKeyword(const std::string &s) {
    static const std::set<std::string> kw = {
        "as", "break", "const", "continue", "crate", "dyn", "else", "enum",
        "extern", "false", "fn", "for", "if", "impl", "in", "let", "loop",
        "match", "mod", "move", "mut", "pub", "ref", "return", "self", "Self",
        "static", "struct", "super", "trait", "true", "type", "unsafe", "use",
        "where", "while", "async", "await", "box", "macro", "override", "try",
        "union"};
    return kw.count(s) != 0;
}

// Make a Python identifier safe to use as a Rust identifier.
static std::string ident(const std::string &name) {
    // self/Self/crate/super are valid where they appear and cannot be raw.
    if (name == "self" || name == "Self" || name == "crate" || name == "super")
        return name;
    if (isRustKeyword(name)) return "r#" + name;
    return name;
}

// Convert a Python string literal token to a Rust string literal.
static std::string convertString(const std::string &lit) {
    if (lit.size() >= 6 &&
        (lit.compare(0, 3, "\"\"\"") == 0 || lit.compare(0, 3, "'''") == 0)) {
        std::string body = lit.substr(3, lit.size() - 6);
        std::string out = "\"";
        for (char c : body) {
            if (c == '"') out += "\\\"";
            else if (c == '\\') out += "\\\\";
            else if (c == '\n') out += "\\n";
            else if (c == '\r') out += "\\r";
            else out += c;
        }
        return out + "\".to_string()";
    }
    if (lit.empty()) return "\"\".to_string()";
    char q = lit.front();
    std::string body = lit.substr(1, lit.size() - 2);
    if (q == '"') return lit + ".to_string()";  // already double-quoted
    // Single-quoted -> double-quoted, escaping embedded double quotes.
    std::string out = "\"";
    for (char c : body) {
        if (c == '"') out += "\\\"";
        else out += c;
    }
    return out + "\".to_string()";
}

// ---------------------------------------------------------------------------
// Code generator
// ---------------------------------------------------------------------------

class RustGen {
public:
    std::string generate(P::ProgramContext *prog) {
        collectSignatures(prog);
        std::string items;     // top-level fns / structs / impls
        std::string mainBody;  // module-level statements -> fn main

        for (auto *st : prog->stmt()) {
            if (auto *cs = st->compound_stmt()) {
                if (auto *fd = cs->funcdef()) {
                    level_ = 0;
                    items += genFuncdef(fd, /*selfKind=*/"");
                    items += "\n";
                    continue;
                }
                if (auto *cd = cs->classdef()) {
                    level_ = 0;
                    items += genClassdef(cd);
                    items += "\n";
                    continue;
                }
            }
            // module-level if __name__ == "__main__": unwrap into main()
            if (auto *cs = st->compound_stmt()) {
                if (auto *ifs = cs->if_stmt(); ifs && isMainGuard(ifs)) {
                    level_ = 1;
                    genSuite(ifs->suite(0), mainBody);
                    continue;
                }
            }
            level_ = 1;
            genStmt(st, mainBody);
        }

        std::string out;
        out += "#![allow(unused_mut, unused_variables, dead_code, unused_parens,\n";
        out += "         unused_imports, non_snake_case, unreachable_code)]\n";
        out += "use std::collections::{HashMap, HashSet};\n\n";
        out += items;
        if (!mainBody.empty()) {
            out += "fn main() {\n";
            out += mainBody;
            out += "}\n";
        } else if (out.find("fn main") == std::string::npos) {
            out += "fn main() {}\n";
        }
        return out;
    }

private:
    int level_ = 0;
    std::set<std::string> declared_;       // names already `let`-bound in scope
    std::set<std::string> tupleVars_;      // names known to hold tuples
    std::set<std::string> collectionVars_; // names holding Vec/HashMap/HashSet
    std::set<std::string> dictVars_;       // names holding a dict (HashMap)
    std::set<std::string> funcAgg_;        // functions returning a collection/tuple
    std::set<std::string> classNames_;     // declared class names

    // One pass to learn class names and which functions return aggregates,
    // so call sites and print formatting can be generated correctly.
    void collectSignatures(P::ProgramContext *prog) {
        for (auto *st : prog->stmt()) {
            auto *cs = st->compound_stmt();
            if (!cs) continue;
            if (auto *fd = cs->funcdef()) {
                if (fd->ARROW() && isAggType(fd->type()))
                    funcAgg_.insert(fd->ID()->getText());
            } else if (auto *cd = cs->classdef()) {
                classNames_.insert(cd->ID()->getText());
            }
        }
    }

    std::string pad() const { return std::string(level_ * 4, ' '); }

    // ---- type annotations -------------------------------------------------
    std::string genType(P::TypeContext *t) {
        if (!t) return "i64";
        if (t->NONE()) return "()";
        std::string name = t->ID()->getText();
        auto subs = t->type();
        if (subs.empty()) {
            if (name == "int") return "i64";
            if (name == "float") return "f64";
            if (name == "bool") return "bool";
            if (name == "str") return "String";
            if (name == "None") return "()";
            return name;  // user-defined class name
        }
        // parametrised: list[T], tuple[...], dict[K,V], set[T]
        std::vector<std::string> args;
        for (auto *s : subs) args.push_back(genType(s));
        if (name == "list" || name == "List") return "Vec<" + args[0] + ">";
        if (name == "set" || name == "Set") return "HashSet<" + args[0] + ">";
        if (name == "dict" || name == "Dict") {
            std::string k = args.size() > 0 ? args[0] : "i64";
            std::string v = args.size() > 1 ? args[1] : "i64";
            return "HashMap<" + k + ", " + v + ">";
        }
        if (name == "tuple" || name == "Tuple") {
            std::string r = "(";
            for (size_t i = 0; i < args.size(); i++) {
                if (i) r += ", ";
                r += args[i];
            }
            if (args.size() == 1) r += ",";
            return r + ")";
        }
        return name;
    }

    bool typeIsTuple(P::TypeContext *t) {
        if (!t || !t->ID()) return false;
        std::string n = t->ID()->getText();
        return (n == "tuple" || n == "Tuple") && !t->type().empty();
    }
    bool typeIsDict(P::TypeContext *t) {
        if (!t || !t->ID()) return false;
        std::string n = t->ID()->getText();
        return n == "dict" || n == "Dict";
    }
    bool typeIsListLike(P::TypeContext *t) {
        if (!t || !t->ID()) return false;
        std::string n = t->ID()->getText();
        return n == "list" || n == "List" || n == "set" || n == "Set";
    }
    bool isAggType(P::TypeContext *t) {
        return typeIsTuple(t) || typeIsDict(t) || typeIsListLike(t);
    }
    // record the aggregate/tuple kind of a variable from its annotation
    void noteVarType(const std::string &name, P::TypeContext *t) {
        if (typeIsTuple(t)) tupleVars_.insert(name);
        else if (typeIsDict(t)) { dictVars_.insert(name); collectionVars_.insert(name); }
        else if (typeIsListLike(t)) collectionVars_.insert(name);
    }

    // ---- functions / classes ---------------------------------------------
    std::string genFuncdef(P::FuncdefContext *fd, const std::string &selfKind) {
        auto savedDeclared = declared_;
        auto savedTuples = tupleVars_;
        auto savedColl = collectionVars_;
        auto savedDict = dictVars_;
        declared_.clear();
        tupleVars_.clear();
        collectionVars_.clear();
        dictVars_.clear();

        std::string name = fd->ID()->getText();
        std::string sig = pad() + "fn " + ident(name) + "(";

        std::vector<std::string> params;
        if (!selfKind.empty()) params.push_back(selfKind);  // &self / &mut self
        if (auto *ps = fd->parameters()) {
            for (auto *p : ps->param()) {
                std::string pname = p->ID()->getText();
                if (pname == "self") continue;  // handled via selfKind
                declared_.insert(pname);
                std::string ptype = genType(p->type());
                if (p->type()) noteVarType(pname, p->type());
                params.push_back(ident(pname) + ": " + ptype);
            }
        }
        for (size_t i = 0; i < params.size(); i++) {
            if (i) sig += ", ";
            sig += params[i];
        }
        sig += ")";
        if (fd->ARROW()) sig += " -> " + genType(fd->type());

        std::string body;
        level_++;
        genSuite(fd->suite(), body);
        level_--;
        std::string out = sig + " {\n" + body + pad() + "}\n";

        declared_ = savedDeclared;
        tupleVars_ = savedTuples;
        collectionVars_ = savedColl;
        dictVars_ = savedDict;
        return out;
    }

    std::string genClassdef(P::ClassdefContext *cd) {
        std::string name = cd->ID()->getText();
        // Gather method funcdefs and field names (from self.X = ... in any method).
        std::vector<P::FuncdefContext *> methods;
        std::vector<std::string> fields;
        std::set<std::string> seenField;

        auto *suite = cd->suite();
        std::vector<P::StmtContext *> bodyStmts;
        if (suite->simple_stmt())
            ;  // class with single simple stmt (e.g. pass) -> no members
        else
            bodyStmts = suite->stmt();

        for (auto *st : bodyStmts) {
            if (auto *cs = st->compound_stmt())
                if (auto *fd = cs->funcdef()) methods.push_back(fd);
        }
        // fields: scan every method for `self.NAME = ...`
        for (auto *m : methods) collectFields(m->suite(), fields, seenField);

        std::string out;
        out += "struct " + ident(name) + " {\n";
        for (auto &f : fields) out += "    " + ident(f) + ": i64,\n";
        out += "}\n\n";
        out += "impl " + ident(name) + " {\n";
        level_ = 1;
        for (auto *m : methods) {
            std::string mname = m->ID()->getText();
            if (mname == "__init__") {
                out += genConstructor(m, name, fields);
            } else {
                bool mutates = methodMutatesSelf(m->suite());
                out += genFuncdef(m, mutates ? "&mut self" : "&self");
            }
            out += "\n";
        }
        level_ = 0;
        out += "}\n";
        return out;
    }

    std::string genConstructor(P::FuncdefContext *fd, const std::string &cls,
                               const std::vector<std::string> &fields) {
        auto savedDeclared = declared_;
        declared_.clear();
        std::string sig = pad() + "fn new(";
        std::vector<std::string> params;
        if (auto *ps = fd->parameters()) {
            for (auto *p : ps->param()) {
                std::string pname = p->ID()->getText();
                if (pname == "self") continue;
                declared_.insert(pname);
                params.push_back(ident(pname) + ": " + genType(p->type()));
            }
        }
        for (size_t i = 0; i < params.size(); i++) {
            if (i) sig += ", ";
            sig += params[i];
        }
        sig += ") -> Self {\n";

        // Translate the body, mapping `self.f = expr` into struct initialisers.
        std::vector<std::pair<std::string, std::string>> inits;
        collectInits(fd->suite(), inits);

        level_++;
        std::string body = pad() + ident(cls) + " {\n";
        level_++;
        std::set<std::string> set;
        for (auto &kv : inits) {
            body += pad() + ident(kv.first) + ": " + kv.second + ",\n";
            set.insert(kv.first);
        }
        for (auto &f : fields)
            if (!set.count(f)) body += pad() + ident(f) + ": 0,\n";
        level_--;
        body += pad() + "}\n";
        level_--;
        std::string out = sig + body + pad() + "}\n";
        declared_ = savedDeclared;
        return out;
    }

    // collect `self.NAME = expr` initialisers in order
    void collectInits(P::SuiteContext *suite,
                      std::vector<std::pair<std::string, std::string>> &out) {
        std::vector<P::StmtContext *> stmts;
        if (auto *ss = suite->simple_stmt()) {
            // not expected for __init__, ignore
        } else {
            stmts = suite->stmt();
        }
        for (auto *st : stmts) {
            auto *ss = st->simple_stmt();
            if (!ss) continue;
            auto *es = ss->small_stmt()->expr_stmt();
            if (!es) continue;
            if (es->ASSIGN().empty() || es->annassign()) continue;
            auto *lhs = es->testlist(0);
            if (lhs->expr().size() != 1) continue;
            auto *me = dynamic_cast<P::MemberExprContext *>(lhs->expr(0));
            if (!me) continue;
            std::string base = exprText(me->expr());
            if (base != "self") continue;
            std::string field = me->ID()->getText();
            std::string val = genExpr(es->testlist().back()->expr(0));
            out.push_back({field, val});
        }
    }

    void collectFields(P::SuiteContext *suite, std::vector<std::string> &fields,
                       std::set<std::string> &seen) {
        std::vector<std::pair<std::string, std::string>> inits;
        collectInits(suite, inits);
        for (auto &kv : inits)
            if (!seen.count(kv.first)) {
                seen.insert(kv.first);
                fields.push_back(kv.first);
            }
    }

    bool methodMutatesSelf(P::SuiteContext *suite) {
        std::vector<std::pair<std::string, std::string>> inits;
        collectInits(suite, inits);
        return !inits.empty();
    }

    // ---- statements -------------------------------------------------------
    void genSuite(P::SuiteContext *s, std::string &out) {
        if (auto *ss = s->simple_stmt()) {
            genSimple(ss, out);
            return;
        }
        for (auto *st : s->stmt()) genStmt(st, out);
    }

    void genStmt(P::StmtContext *st, std::string &out) {
        if (auto *ss = st->simple_stmt()) {
            genSimple(ss, out);
            return;
        }
        genCompound(st->compound_stmt(), out);
    }

    void genSimple(P::Simple_stmtContext *ss, std::string &out) {
        auto *sm = ss->small_stmt();
        if (auto *es = sm->expr_stmt()) {
            genExprStmt(es, out);
        } else if (auto *rs = sm->return_stmt()) {
            if (auto *tl = rs->testlist())
                out += pad() + "return " + genTestlist(tl) + ";\n";
            else
                out += pad() + "return;\n";
        } else if (sm->pass_stmt()) {
            out += pad() + "// pass\n";
        } else if (auto *fs = sm->flow_stmt()) {
            out += pad() + (fs->BREAK() ? "break;\n" : "continue;\n");
        } else if (auto *rz = sm->raise_stmt()) {
            if (!rz->expr().empty())
                out += pad() + "panic!(\"" + escape(rz->expr(0)->getText()) + "\");\n";
            else
                out += pad() + "panic!(\"exception\");\n";
        } else if (auto *im = sm->import_stmt()) {
            out += pad() + "// " + im->getText() + "\n";
        }
    }

    void genExprStmt(P::Expr_stmtContext *es, std::string &out) {
        // annotated assignment: name: T (= value)?
        if (auto *ann = es->annassign()) {
            auto *lhs = es->testlist(0);
            std::string target = (lhs->expr().size() == 1)
                                     ? exprText(lhs->expr(0))
                                     : genTestlist(lhs);
            std::string rty = genType(ann->type());
            noteVarType(target, ann->type());
            if (ann->testlist()) {
                out += pad() + "let mut " + ident(target) + ": " + rty + " = " +
                       genTestlist(ann->testlist()) + ";\n";
            } else {
                out += pad() + "let mut " + ident(target) + ": " + rty + ";\n";
            }
            declared_.insert(target);
            return;
        }
        // plain expression statement (no '=')
        if (es->ASSIGN().empty()) {
            out += pad() + genTestlist(es->testlist(0)) + ";\n";
            return;
        }
        // assignment, possibly chained: t0 = t1 = ... = value
        auto tls = es->testlist();
        std::string rhs = genTestlist(tls.back());
        // track tuple/aggregate-ness of RHS so LHS names inherit the kind
        bool rhsTuple = testlistIsTuple(tls.back());
        bool rhsAgg = false, rhsDict = false;
        if (tls.back()->expr().size() == 1) {
            auto *re = tls.back()->expr(0);
            if (!rhsTuple) {
                rhsTuple = exprIsTupleAtom(re);
                if (auto *id = asIdAtom(re))
                    if (tupleVars_.count(id->ID()->getText())) rhsTuple = true;
            }
            rhsAgg = isAggExpr(re);
            rhsDict = isDictExpr(re);
        }
        for (size_t i = 0; i + 1 < tls.size(); i++) {
            assignTo(tls[i], rhs, rhsTuple, rhsAgg, rhsDict, out);
        }
    }

    void assignTo(P::TestlistContext *lhs, const std::string &rhs, bool rhsTuple,
                  bool rhsAgg, bool rhsDict, std::string &out) {
        // tuple unpacking: a, b = ...
        if (lhs->expr().size() > 1 || !lhs->COMMA().empty()) {
            std::vector<std::string> names;
            bool allDeclared = true;
            for (auto *e : lhs->expr()) {
                std::string n = exprText(e);
                names.push_back(n);
                if (!declared_.count(n)) allDeclared = false;
            }
            std::string pat;
            for (size_t i = 0; i < names.size(); i++) {
                if (i) pat += ", ";
                pat += (allDeclared ? "" : "mut ") + ident(names[i]);
            }
            if (allDeclared)
                out += pad() + "(" + pat + ") = " + rhs + ";\n";
            else {
                out += pad() + "let (" + pat + ") = " + rhs + ";\n";
                for (auto &n : names) declared_.insert(n);
            }
            return;
        }
        // single target
        auto *e = lhs->expr(0);
        if (auto *id = asIdAtom(e)) {
            std::string n = id->ID()->getText();
            if (rhsTuple) tupleVars_.insert(n);
            if (rhsAgg) collectionVars_.insert(n);
            if (rhsDict) dictVars_.insert(n);
            if (declared_.count(n))
                out += pad() + ident(n) + " = " + rhs + ";\n";
            else {
                out += pad() + "let mut " + ident(n) + " = " + rhs + ";\n";
                declared_.insert(n);
            }
        } else {
            // member / index target: obj.f = v   or   v[i] = v
            out += pad() + genExpr(e) + " = " + rhs + ";\n";
        }
    }

    void genCompound(P::Compound_stmtContext *cs, std::string &out) {
        if (auto *i = cs->if_stmt()) return genIf(i, out);
        if (auto *w = cs->while_stmt()) return genWhile(w, out);
        if (auto *f = cs->for_stmt()) return genFor(f, out);
        if (auto *t = cs->try_stmt()) return genTry(t, out);
        if (auto *fd = cs->funcdef()) {
            out += genFuncdef(fd, "");
            return;
        }
        if (auto *cd = cs->classdef()) {
            out += genClassdef(cd);
            return;
        }
    }

    void genIf(P::If_stmtContext *i, std::string &out) {
        auto exprs = i->expr();
        auto suites = i->suite();
        out += pad() + "if " + genExpr(exprs[0]) + " {\n";
        level_++;
        genSuite(suites[0], out);
        level_--;
        size_t si = 1;
        for (size_t k = 0; k < i->ELIF().size(); k++, si++) {
            out += pad() + "} else if " + genExpr(exprs[si]) + " {\n";
            level_++;
            genSuite(suites[si], out);
            level_--;
        }
        if (i->ELSE()) {
            out += pad() + "} else {\n";
            level_++;
            genSuite(suites.back(), out);
            level_--;
        }
        out += pad() + "}\n";
    }

    void genWhile(P::While_stmtContext *w, std::string &out) {
        out += pad() + "while " + genExpr(w->expr()) + " {\n";
        level_++;
        genSuite(w->suite(0), out);
        level_--;
        out += pad() + "}\n";
    }

    void genFor(P::For_stmtContext *f, std::string &out) {
        std::string target = genTargetList(f->target_list());
        // mark loop-bound names as declared
        for (auto *t : f->target_list()->target())
            if (t->ID()) declared_.insert(t->ID()->getText());

        std::string iter;
        auto *tl = f->testlist();
        if (tl->expr().size() == 1) {
            if (auto *rng = asRange(tl->expr(0))) {
                iter = genRange(rng);
            } else {
                iter = genExpr(tl->expr(0)) + ".iter().cloned()";
            }
        } else {
            iter = genTestlist(tl) + ".iter().cloned()";
        }
        out += pad() + "for " + target + " in " + iter + " {\n";
        level_++;
        genSuite(f->suite(0), out);
        level_--;
        out += pad() + "}\n";
    }

    void genTry(P::Try_stmtContext *t, std::string &out) {
        out += pad() + "// try / except is not directly supported in Rust\n";
        out += pad() + "{\n";
        level_++;
        genSuite(t->suite(0), out);
        level_--;
        out += pad() + "}\n";
        // except / else / finally bodies are emitted as comments for reference
        if (t->FINALLY()) {
            out += pad() + "// finally:\n";
            genSuite(t->suite().back(), out);
        }
    }

    // ---- targets ----------------------------------------------------------
    std::string genTargetList(P::Target_listContext *tl) {
        auto targets = tl->target();
        if (targets.size() == 1 && tl->COMMA().empty())
            return genTarget(targets[0]);
        std::string r = "(";
        for (size_t i = 0; i < targets.size(); i++) {
            if (i) r += ", ";
            r += genTarget(targets[i]);
        }
        return r + ")";
    }

    std::string genTarget(P::TargetContext *t) {
        if (t->ID()) return ident(t->ID()->getText());
        if (t->target_list()) return genTargetList(t->target_list());
        return "_";
    }

    // ---- testlist (tuple or single expr) ----------------------------------
    bool testlistIsTuple(P::TestlistContext *tl) {
        return tl->expr().size() > 1 || !tl->COMMA().empty();
    }

    std::string genTestlist(P::TestlistContext *tl) {
        auto exprs = tl->expr();
        if (exprs.size() == 1 && tl->COMMA().empty()) return genExpr(exprs[0]);
        std::string r = "(";
        for (size_t i = 0; i < exprs.size(); i++) {
            if (i) r += ", ";
            r += genExpr(exprs[i]);
        }
        if (exprs.size() == 1) r += ",";  // single-element tuple (x,)
        return r + ")";
    }

    // ---- expressions ------------------------------------------------------
    std::string genExpr(P::ExprContext *e) {
        if (auto *c = dynamic_cast<P::AtomExprContext *>(e))
            return genAtom(c->atom());
        if (auto *c = dynamic_cast<P::CallExprContext *>(e)) return genCall(c);
        if (auto *c = dynamic_cast<P::IndexExprContext *>(e)) return genIndex(c);
        if (auto *c = dynamic_cast<P::MemberExprContext *>(e))
            return genExpr(c->expr()) + "." + ident(c->ID()->getText());
        if (auto *c = dynamic_cast<P::UnaryExprContext *>(e)) {
            std::string inner = genExpr(c->expr());
            return c->MINUS() ? "(-" + inner + ")" : inner;
        }
        if (auto *c = dynamic_cast<P::MulDivExprContext *>(e)) {
            std::string op = c->STAR() ? " * " : (c->DIV() ? " / " : " % ");
            return "(" + genExpr(c->expr(0)) + op + genExpr(c->expr(1)) + ")";
        }
        if (auto *c = dynamic_cast<P::AddSubExprContext *>(e)) {
            std::string op = c->PLUS() ? " + " : " - ";
            return "(" + genExpr(c->expr(0)) + op + genExpr(c->expr(1)) + ")";
        }
        if (auto *c = dynamic_cast<P::CompExprContext *>(e)) {
            std::string op = c->LT()    ? " < "
                             : c->GT()  ? " > "
                             : c->LE()  ? " <= "
                             : c->GE()  ? " >= "
                             : c->EQ()  ? " == "
                                        : " != ";
            return "(" + genExpr(c->expr(0)) + op + genExpr(c->expr(1)) + ")";
        }
        if (auto *c = dynamic_cast<P::NotExprContext *>(e))
            return "(!" + genExpr(c->expr()) + ")";
        if (auto *c = dynamic_cast<P::AndExprContext *>(e))
            return "(" + genExpr(c->expr(0)) + " && " + genExpr(c->expr(1)) + ")";
        if (auto *c = dynamic_cast<P::OrExprContext *>(e))
            return "(" + genExpr(c->expr(0)) + " || " + genExpr(c->expr(1)) + ")";
        return e->getText();
    }

    std::string genAtom(P::AtomContext *a) {
        if (auto *c = dynamic_cast<P::IntAtomContext *>(a)) return c->INT()->getText();
        if (auto *c = dynamic_cast<P::FloatAtomContext *>(a)) return c->FLOAT()->getText();
        if (auto *c = dynamic_cast<P::StringAtomContext *>(a))
            return convertString(c->STRING()->getText());
        if (dynamic_cast<P::TrueAtomContext *>(a)) return "true";
        if (dynamic_cast<P::FalseAtomContext *>(a)) return "false";
        if (dynamic_cast<P::NoneAtomContext *>(a)) return "()";
        if (auto *c = dynamic_cast<P::IdAtomContext *>(a)) return ident(c->ID()->getText());
        if (auto *c = dynamic_cast<P::ListAtomContext *>(a)) return genList(c->list_maker());
        if (auto *c = dynamic_cast<P::SetDictAtomContext *>(a))
            return genSetOrDict(c->set_or_dict());
        if (auto *c = dynamic_cast<P::GroupOrTupleAtomContext *>(a)) {
            auto *tl = c->testlist();
            if (!tl) return "()";  // empty tuple
            return genTestlist(tl);
        }
        return a->getText();
    }

    std::string genCall(P::CallExprContext *c) {
        // builtin function shortcuts
        if (auto *id = asIdAtom(c->expr())) {
            std::string fn = id->ID()->getText();
            std::vector<std::string> args = callArgs(c->arglist());
            if (fn == "print") return genPrint(posArgExprs(c->arglist()));
            if (fn == "len" && args.size() == 1) return "(" + args[0] + ".len() as i64)";
            if (fn == "str" && args.size() == 1) return args[0] + ".to_string()";
            if (fn == "int" && args.size() == 1) return "(" + args[0] + " as i64)";
            if (fn == "float" && args.size() == 1) return "(" + args[0] + " as f64)";
            if (fn == "abs" && args.size() == 1) return "(" + args[0] + ").abs()";
            if (fn == "min" && args.size() == 2) return "(" + args[0] + ").min(" + args[1] + ")";
            if (fn == "max" && args.size() == 2) return "(" + args[0] + ").max(" + args[1] + ")";
            // class instantiation: ClassName(args) -> ClassName::new(args)
            if (classNames_.count(fn)) {
                std::string r = ident(fn) + "::new(";
                for (size_t i = 0; i < args.size(); i++) {
                    if (i) r += ", ";
                    r += args[i];
                }
                return r + ")";
            }
        }
        std::string callee = genExpr(c->expr());
        // method renamings: list.append(x) -> Vec::push
        std::string suffix;
        if (callee.size() > 7 && callee.compare(callee.size() - 7, 7, ".append") == 0)
            callee = callee.substr(0, callee.size() - 7) + ".push";
        std::string r = callee + "(";
        auto args = callArgs(c->arglist());
        for (size_t i = 0; i < args.size(); i++) {
            if (i) r += ", ";
            r += args[i];
        }
        return r + ")";
    }

    std::vector<std::string> callArgs(P::ArglistContext *al) {
        std::vector<std::string> out;
        if (!al) return out;
        for (auto *arg : al->argument()) {
            if (auto *pa = dynamic_cast<P::PosArgContext *>(arg))
                out.push_back(genExpr(pa->expr()));
            else if (auto *ka = dynamic_cast<P::KwArgContext *>(arg))
                out.push_back(genExpr(ka->expr()));  // keyword name dropped
        }
        return out;
    }

    std::vector<P::ExprContext *> posArgExprs(P::ArglistContext *al) {
        std::vector<P::ExprContext *> out;
        if (!al) return out;
        for (auto *arg : al->argument())
            if (auto *pa = dynamic_cast<P::PosArgContext *>(arg))
                out.push_back(pa->expr());
        return out;
    }

    std::string genPrint(const std::vector<P::ExprContext *> &args) {
        if (args.empty()) return "println!()";
        std::string fmt;
        for (size_t i = 0; i < args.size(); i++) {
            if (i) fmt += " ";
            fmt += needsDebug(args[i]) ? "{:?}" : "{}";
        }
        std::string r = "println!(\"" + fmt + "\"";
        for (auto *a : args) r += ", " + genExpr(a);
        return r + ")";
    }

    std::string genIndex(P::IndexExprContext *c) {
        std::string base = genExpr(c->expr());
        auto *sub = c->subscript();
        if (auto *sl = sub->slice()) return base + "[" + genSlice(sl) + "]";
        auto *idx = sub->expr();
        // dict access: d[key] -> d[&(key)]
        if (auto *id = asIdAtom(c->expr()))
            if (dictVars_.count(id->ID()->getText()))
                return base + "[&(" + genExpr(idx) + ")]";
        // tuple element access: t[0] -> t.0
        if (auto *id = asIdAtom(c->expr())) {
            if (tupleVars_.count(id->ID()->getText())) {
                if (auto *ia = dynamic_cast<P::IntAtomContext *>(atomOf(idx)))
                    return base + "." + ia->INT()->getText();
            }
        }
        // negative literal index: t[-1] -> t[t.len() - 1]
        if (auto *u = dynamic_cast<P::UnaryExprContext *>(idx)) {
            if (u->MINUS())
                if (auto *ia = dynamic_cast<P::IntAtomContext *>(atomOf(u->expr())))
                    return base + "[" + base + ".len() - " + ia->INT()->getText() + "]";
        }
        if (dynamic_cast<P::IntAtomContext *>(atomOf(idx)))
            return base + "[" + genExpr(idx) + "]";
        return base + "[(" + genExpr(idx) + ") as usize]";
    }

    std::string genSlice(P::SliceContext *sl) {
        // [a:b]  (step is not supported)
        auto exprs = sl->expr();
        // figure out which positions are present by walking children
        std::string lo, hi;
        size_t colon = 0, ei = 0;
        for (auto *ch : sl->children) {
            if (ch->getText() == ":") {
                colon++;
            } else if (ei < exprs.size() &&
                       ch == static_cast<antlr4::tree::ParseTree *>(exprs[ei])) {
                std::string v = genExpr(exprs[ei]);
                if (colon == 0) lo = v;
                else hi = v;
                ei++;
            }
        }
        return lo + ".." + hi;
    }

    // ---- collections ------------------------------------------------------
    std::string genList(P::List_makerContext *lm) {
        if (lm->comp_clause()) {
            return genComprehension(lm->expr(0), lm->comp_clause(), "Vec<_>", "");
        }
        auto exprs = lm->expr();
        std::string r = "vec![";
        for (size_t i = 0; i < exprs.size(); i++) {
            if (i) r += ", ";
            r += genExpr(exprs[i]);
        }
        return r + "]";
    }

    std::string genSetOrDict(P::Set_or_dictContext *sd) {
        bool isDict = !sd->dict_kv().empty();
        if (sd->comp_clause()) {
            if (isDict) {
                auto *kv = sd->dict_kv(0);
                std::string kvexpr = "(" + genExpr(kv->expr(0)) + ", " +
                                     genExpr(kv->expr(1)) + ")";
                return genComprehensionRaw(kvexpr, sd->comp_clause(), "HashMap<_, _>");
            }
            return genComprehension(sd->expr(0), sd->comp_clause(), "HashSet<_>", "");
        }
        if (isDict) {
            std::string r = "HashMap::from([";
            auto kvs = sd->dict_kv();
            for (size_t i = 0; i < kvs.size(); i++) {
                if (i) r += ", ";
                r += "(" + genExpr(kvs[i]->expr(0)) + ", " +
                     genExpr(kvs[i]->expr(1)) + ")";
            }
            return r + "])";
        }
        auto exprs = sd->expr();
        if (exprs.empty()) return "HashMap::new()";  // {} is an empty dict
        std::string r = "HashSet::from([";
        for (size_t i = 0; i < exprs.size(); i++) {
            if (i) r += ", ";
            r += genExpr(exprs[i]);
        }
        return r + "])";
    }

    // [expr for target in iter (if cond)?]  ->  iterator chain
    std::string genComprehension(P::ExprContext *body, P::Comp_clauseContext *cc,
                                 const std::string &collectTy, const std::string &) {
        return genComprehensionRaw(genExpr(body), cc, collectTy);
    }

    std::string genComprehensionRaw(const std::string &bodyExpr,
                                    P::Comp_clauseContext *cc,
                                    const std::string &collectTy) {
        std::string target = genTargetList(cc->target_list());
        std::string chain;
        if (auto *rng = asRange(cc->expr(0)))
            chain = "(" + genRange(rng) + ")";  // a range is itself an iterator
        else
            chain = genExpr(cc->expr(0)) + ".iter().cloned()";  // borrow, don't move
        if (cc->IF())
            chain += ".filter(|" + target + "| " + genExpr(cc->expr(1)) + ")";
        chain += ".map(|" + target + "| " + bodyExpr + ")";
        chain += ".collect::<" + collectTy + ">()";
        return chain;
    }

    // ---- predicates / utilities -------------------------------------------
    static P::IdAtomContext *asIdAtom(P::ExprContext *e) {
        if (auto *ae = dynamic_cast<P::AtomExprContext *>(e))
            return dynamic_cast<P::IdAtomContext *>(ae->atom());
        return nullptr;
    }
    static P::AtomContext *atomOf(P::ExprContext *e) {
        if (auto *ae = dynamic_cast<P::AtomExprContext *>(e)) return ae->atom();
        return nullptr;
    }
    // true if `e` is a parenthesised tuple atom, e.g. (1, 2) or (42,) or ()
    static bool exprIsTupleAtom(P::ExprContext *e) {
        auto *a = atomOf(e);
        auto *g = dynamic_cast<P::GroupOrTupleAtomContext *>(a);
        if (!g) return false;
        auto *tl = g->testlist();
        if (!tl) return true;  // empty tuple ()
        return tl->expr().size() > 1 || !tl->COMMA().empty();
    }
    // true if `e` evaluates to a Vec / HashMap / HashSet
    bool isAggExpr(P::ExprContext *e) {
        auto *a = atomOf(e);
        if (dynamic_cast<P::ListAtomContext *>(a)) return true;
        if (dynamic_cast<P::SetDictAtomContext *>(a)) return true;
        if (auto *id = asIdAtom(e))
            if (collectionVars_.count(id->ID()->getText())) return true;
        if (auto *ce = dynamic_cast<P::CallExprContext *>(e))
            if (auto *id = asIdAtom(ce->expr()))
                if (funcAgg_.count(id->ID()->getText())) return true;
        return false;
    }
    // true if `e` evaluates to a dict (HashMap)
    bool isDictExpr(P::ExprContext *e) {
        auto *a = atomOf(e);
        if (auto *sd = dynamic_cast<P::SetDictAtomContext *>(a)) {
            auto *s = sd->set_or_dict();
            if (!s->dict_kv().empty()) return true;            // {k: v ...}
            if (s->expr().empty() && !s->comp_clause()) return true;  // {} empty dict
            return false;                                       // set
        }
        if (auto *id = asIdAtom(e)) return dictVars_.count(id->ID()->getText()) != 0;
        return false;
    }
    // does this expression need {:?} (Debug) formatting in println! ?
    bool needsDebug(P::ExprContext *e) {
        return isAggExpr(e) || exprIsTupleAtom(e) ||
               (asIdAtom(e) && tupleVars_.count(asIdAtom(e)->ID()->getText()));
    }
    // returns the call if `e` is a call to range(...)
    static P::CallExprContext *asRange(P::ExprContext *e) {
        if (auto *ce = dynamic_cast<P::CallExprContext *>(e))
            if (auto *id = asIdAtom(ce->expr()))
                if (id->ID()->getText() == "range") return ce;
        return nullptr;
    }
    std::string genRange(P::CallExprContext *c) {
        auto args = callArgs(c->arglist());
        if (args.size() == 1) return "0.." + args[0];
        if (args.size() == 2) return args[0] + ".." + args[1];
        if (args.size() >= 3)
            return "(" + args[0] + ".." + args[1] + ").step_by(" + args[2] +
                   " as usize)";
        return "0..0";
    }

    std::string exprText(P::ExprContext *e) {
        if (auto *id = asIdAtom(e)) return id->ID()->getText();
        return genExpr(e);
    }

    static bool isMainGuard(P::If_stmtContext *i) {
        auto *cmp = dynamic_cast<P::CompExprContext *>(i->expr(0));
        if (!cmp || !cmp->EQ()) return false;
        std::string t = cmp->getText();
        return t.find("__name__") != std::string::npos &&
               t.find("__main__") != std::string::npos;
    }

    static std::string escape(const std::string &s) {
        std::string r;
        for (char c : s) {
            if (c == '"' || c == '\\') r += '\\';
            r += c;
        }
        return r;
    }
};

// ---------------------------------------------------------------------------
// Error listener that counts syntax errors
// ---------------------------------------------------------------------------
class CountingErrorListener : public antlr4::BaseErrorListener {
public:
    int count = 0;
    void syntaxError(antlr4::Recognizer *, antlr4::Token *, size_t line,
                     size_t col, const std::string &msg,
                     std::exception_ptr) override {
        count++;
        std::cerr << "Syntax error (line " << line << ":" << col << "): " << msg
                  << "\n";
    }
};

int main(int argc, char **argv) {
    if (argc < 2) {
        std::cerr << "Usage: pyrust <input.py> [-o output.rs]\n";
        return 2;
    }
    std::string inPath = argv[1];
    std::string outPath;
    for (int i = 2; i < argc; i++) {
        std::string a = argv[i];
        if (a == "-o" && i + 1 < argc) outPath = argv[++i];
    }
    if (outPath.empty()) {
        outPath = inPath;
        auto dot = outPath.find_last_of('.');
        if (dot != std::string::npos) outPath = outPath.substr(0, dot);
        outPath += ".rs";
    }

    std::ifstream ifs(inPath, std::ios::binary);
    if (!ifs) {
        std::cerr << "Cannot open input file: " << inPath << "\n";
        return 2;
    }
    std::stringstream buf;
    buf << ifs.rdbuf();
    std::string source = buf.str();

    antlr4::ANTLRInputStream input(source);
    PythonRustLexer lexer(&input);
    antlr4::CommonTokenStream tokens(&lexer);
    PythonRustParser parser(&tokens);

    CountingErrorListener errs;
    lexer.removeErrorListeners();
    parser.removeErrorListeners();
    parser.addErrorListener(&errs);

    P::ProgramContext *tree = parser.program();
    if (errs.count > 0) {
        std::cerr << "Aborting: " << errs.count << " syntax error(s).\n";
        return 1;
    }

    RustGen gen;
    std::string rust = gen.generate(tree);

    std::ofstream ofs(outPath, std::ios::binary);
    if (!ofs) {
        std::cerr << "Cannot write output file: " << outPath << "\n";
        return 2;
    }
    ofs << rust;
    std::cerr << "Wrote " << outPath << "\n";
    return 0;
}
